#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use CViniciusSDias\PHPHadoop\Command\{GenerateFakeData, IdadesMapper, IdadesReducer};
use Symfony\Component\Console\Application;

$app = new Application('PHP Hadoop', '@package_version@');
$app->add(new GenerateFakeData());
$app->add(new IdadesMapper());
$app->add(new IdadesReducer());
$app->run();
